apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "testtools-container.labels" . | nindent 4 }}
  name: {{ include "testtools-container.fullname" . }}
spec:
  ports:
    - name: http
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    {{- include "testtools-container.selectorLabels" . | nindent 6 }}
